version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  fledge:
    image: 'fledge'
    networks:
      - app-tier
    ports:
      - '8081:8081'
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - dpsim

  dpsim:
    image: 'dpsim-iec104'
    networks:
      - app-tier
    ports:
      - '2404:2404'
    environment:
      - DPSIM_SIMULATION_LOOP=true
